# From https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b
name: Deployment
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-course-schedulizer
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: update-pnpm-version
        run: |
          pnpm install -g pnpm@latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: pnpm install
        working-directory: ${{env.working-directory}}
      - name: Build Page
        run: pnpm run build
        working-directory: ${{env.working-directory}}
      - name: Remove gh-pages Cache
        run: rm -rf node_modules/gh-pages/.cache
        working-directory: ${{env.working-directory}}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./client-course-schedulizer/build
